<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="PDFsharp-MigraDoc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prospecta.Application\Prospecta.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Reporting\Fonts\*.ttf" />
  </ItemGroup>

</Project>
